### ISSUE TITLE
www.czzy77.com这个网站好像不能嗅探

### ISSUE THREAD

**Issue by qazwse4541** [1944876825/sniffing.tools#2]
- name: "czzy77" # 名称
    match: # 资源特征
      - "www.czzy77.com"
    click: # 点击此元素（使用css选择器）
      - "video" # 点击video标签
    white: # 资源链接特征 白名单
      - ".mp4?bid="
    black: # 资源链接特征 黑名单
      - "gg.m3u8"

  - name: "czzy771号" # 名称
    match: # 资源特征
      - "www.czzy77.com"
    click: # 点击此元素（使用css选择器）
      - "video" # 点击video标签
    white: # 资源链接特征 白名单
      - "sf16-sg.larksuitecdn.com"
    black: # 资源链接特征 黑名单
      - "gg.m3u8"

**Comment by 1944876825** [comment]
不配置就能解析成功
